### ISSUE TITLE
Add support for pre-defined configurations?

### ISSUE THREAD

**Issue by monrax** [RobDickinson/supertanker#10]
Vadym mentioned this the other day. Should we provide support for other pre-defined configurations, in addition to making the package versions customizable?

Not sure if this could mean we end up having multiple tags, or if we should instead go one level down and implement this using `supervisord`, or perhaps one level up and use something like terraform/opentofu...

**Comment by monrax** [comment]
@vvasylenko thoughts?

**Comment by RobDickinson** [comment]
The two configurations at present are:
* v6.0.x branch: v6.0 + OpenSearch 2.12 + MongoDB 6
* v6.1.x branch: v6.1 + Datanode + MongoDB 6

(closing this issue but happy to consider any specific suggestions in the future)
