### ISSUE TITLE
Test multinode configuration

### ISSUE THREAD

**Issue by monrax** [RobDickinson/supertanker#7]
Currently, we have only tried supertanker in single-node configuration. We should add support for multiple nodes, and test by adding/removing nodes.

**Comment by monrax** [comment]
extra thought: perhaps `supertanker-worker` could be required?

**Comment by RobDickinson** [comment]
I would love to explore multi-node configurations (and in the helm context 🤞) but I think that may be better scoped as its own research project vs trying to take this on here.

What I really wanted to show with supertanker is that a single-node best-practices Docker configuration can be super friendly, and doesn't require any GL-specific changes to be remixed this way.

I think this idea 👆 might get lost if we layer on too much?

If somebody wants to fork this or borrow code to build their own research project, I'm 100% supportive of that 💪
